version: '3.7'

services:
    app:
        image: 'vanessakovalsky/kingoludo-laravel'
        container_name: shouts-laravel-app
        ports:
            - "8090:80"
        networks:
            - laravel-shouts
        depends_on:
            - mysql
        command: sh -c "/usr/local/bin/initscript.sh && apache2-foreground"
    mysql:
        image: 'mariadb:latest'
        container_name: shouts-laravel-db
        restart: unless-stopped
        ports:
            - "3310:3306"
        environment:
            MARIADB_DATABASE: laravel
            MARIADB_ROOT_PASSWORD: rootpassword
            MARIADB_PASSWORD: larapass
            MARIADB_USER: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel-shouts
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      user: root
      ports:
      - 9091:9090
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus'
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      depends_on:
      - cadvisor
    node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      restart: unless-stopped
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      expose:
        - 9100
    cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      container_name: cadvisor
      ports:
      - 8080:8080
      volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        ports:
        - '3000:3000'
networks:
    laravel-shouts:
        driver: bridge

volumes:
    dbdata: {}
    prometheus_data: {}
